# base colors from https://github.com/EdenEast/nightfox.nvim
# modfied for more contrast

[colors.window]
default = { bg = "#eee6dd", fg = "#575279" }
statusline = { bg = "#d3c9c0", fg = "#333a40" }
statusline_no_focus = { bg = "#d5d1ce" }
end_of_buffer = { fg = "#969896" }
trailing_whitespace = { fg = "#969896" }
match = { bg = "#C1E1C1", fg = "#356E35" }
virtual = { fg = "#969896" }

[colors.cursor]
normal = { bg = "#bbb0aa" }
selection = { bg = "#e1d4c3" }

[colors.window.view]
hint = { bg = "#b7d8eb", fg = "#00576B" }
info = { bg = "#b7d8eb", fg = "#00576B" }
warn = { bg = "#FFD8B2", fg = "#8C4C1F" }
error = { bg = "#FF9E99", fg = "#8A3A5A" }

added = { bg = "#C1E1C1", fg = "#356E35" }
modified = { bg = "#FFD8B2", fg = "#8C4C1F" }
deleted = { bg = "#FF9E99", fg = "#8A3A5A" }

constant = { fg = "#1a6582" }
string =  { fg = "#0d8751" }
keyword = { fg = "#ca6e69" }
operator =  { fg = "#2d81a3" }
type =  { fg = "#916767" }
comment = { fg = "#969896" }
preproc = { fg = "#8c5cc2" }
special = { fg = "#8c5cc2" }
identifier = { fg = "#a5576d" }

[colors.window.completion]
default = { bg = "#e7dccf", fg = "#575279" }
description = { fg = "#969896" }
match = { fg = "#d9605a" }

[colors.window.completion.selected]
default = { bg = "#ddd2c8" }
description = { fg = "#969896" }
match = { fg = "#d9605a" }

[colors.prompt]
default = { bg = "#c2cdcd", fg = "#494565" }
# message = { }
# userinput = { }

[colors.prompt.overlay]
default = { bg = "#e7dccf", fg = "#625c87" }
# title = { }
message = { fg = "#575279" }

[colors.prompt.completion]
default = { bg = "#e7dccf", fg = "#575279" }
description = { fg = "#969896" }
match = { fg = "#d9605a" }

[colors.prompt.completion.selected]
default = { bg = "#ddd2c8" }
description = { fg = "#969896" }
match = { fg = "#d9605a" }

[colors.filetree]
default = { bg = "#eee6dd", fg = "#575279" }
markers = { fg = "#2d81a3" }
directory = { fg = "#9E7777" }

[colors.filetree.selected]
default = { bg = "#ddd2c8" }
directory = { fg = "#9E7777" }
markers = { fg = "#2d81a3" }

[colors.locations]
default = { bg = "#eee6dd", fg = "#575279" }
title = { bg = "#d3c9c0", fg = "#333a40" }
# entry = {  }
group = { fg = "#9E7777" }
markers = { fg = "#2d81a3" }
match = { fg = "#d9605a" }

[colors.locations.selected]
default = { bg = "#ddd2c8" }
match = { fg = "#d9605a" }
markers = { fg = "#2d81a3" }
# entry = { }
group = { fg = "#9E7777" }

[colors.popup]
default = { bg = "#e7dccf", fg = "#625c87" }
