# Colors from https://github.com/sainnhe/everforest/blob/master/palette.md

[variables]
bg = "#2d353b"
fg = "#d3c6aa"

bg_alt = "#3D484D"
bg_alt2 = "#9DA9A0"

green = "#A7C080"
magenta = "#D699B6"
yellow = "#DBBC7F"
orange = "#E69875"
red = "#E67E80"
blue = "#7FBBB3"
aqua = "#83C092"

blue_fg = "#3A515D"
yellow_fg = "#4D4C43"
red_fg = "#514045"
green_fg = "#425047"
gray_fg = "#7A8478"



[colors.window]
default = { bg = "bg", fg = "fg" }
statusline = { bg = "#343F44", fg = "fg" }
statusline_no_focus = { bg = "bg" }
end_of_buffer = { fg = "#475258" }
trailing_whitespace = { fg = "#475258" }
match = { bg = "green", fg = "bg" }
virtual = { fg = "#4F585E" }

[colors.cursor]
normal = { bg = "blue", fg = "bg" }
selection = { bg = "#56635f" }

[colors.window.view]
hint = { bg = "blue_fg", fg = "blue" }
info = { bg = "blue_fg", fg = "blue" }
warn = { bg = "yellow_fg", fg = "yellow" }
error = { bg = "red_fg", fg = "red" }

added = { bg = "green_fg", fg = "green" }
modified = { bg = "yellow_fg", fg = "yellow" }
deleted = { bg = "red_fg", fg = "red" }

constant = { fg = "aqua" }
string =  { fg = "green" }
keyword = { fg = "red" }
operator =  { fg = "orange" }
type =  { fg = "yellow" }
comment = { fg = "#859289" }
preproc = { fg = "#D699B6" }
special = { fg = "yellow" }
identifier = { fg = "blue" }

[colors.window.completion]
default = { bg = "bg_alt", fg = "fg" }
description = {  fg = "#969896" }
match = { fg = "#de935f" }

[colors.window.completion.selected]
default = { bg = "green", fg = "bg" }
# description = { }
match = { fg = "#c55809" }

[colors.prompt]
default = { bg = "#9DA9A0", fg = "bg" }
message = { text_style = "bold" }
# userinput = { }

[colors.prompt.overlay]
default = { bg = "bg_alt", fg = "fg" }
title = { text_style = "bold" }
message = { fg = "fg", text_style = "bold" }

[colors.prompt.completion]
default = { bg = "bg_alt", fg = "fg" }
# description = { }
match = { fg = "#de935f" }

[colors.prompt.completion.selected]
default = { bg = "green", fg = "bg" }
# description = { }
match = { fg = "#c55809" }

[colors.filetree]
default = { bg = "bg", fg = "fg" }
markers = { fg = "gray_fg" }
directory = { fg = "yellow" }

[colors.filetree.selected]
default = { bg = "bg_alt" }
directory = { fg = "yellow" }
markers = { fg = "gray_fg" }

[colors.locations]
default = { bg = "bg", fg = "fg" }
title = { bg = "#4F585E", fg = "fg" }
# entry = {  }
group = { fg = "aqua" }
markers = { fg = "gray_fg" }
match = { fg = "orange" }

[colors.locations.selected]
default = { bg = "bg_alt" }
match = { fg = "orange" }
markers = { fg = "gray_fg" }
# entry = {  }
group = { fg = "aqua" }

[colors.popup]
default = { bg = "#3D484D", fg = "fg" }
