[colors.window]
default = { bg = "#000000" }
statusline = { bg = "#ffffff", fg = "#000000" }
match = { bg = "#FF00FF", fg = "#000000" }
virtual = { fg = "#00ffff" }

[colors.cursor]
normal = { bg = "#ffffff" }
selection = { bg = "#ffffff", fg = "#000000" }

[colors.window.view]
hint = { bg = "#0000FF", fg = "#000000" }
info = { bg = "#0000FF", fg = "#000000" }
warn = { bg = "#FFFF00", fg = "#000000" }
error = { bg = "#FF0000", fg = "#000000" }

added = { bg = "#00FF00", fg = "#000000" }
modified = { bg = "#FFFF00", fg = "#000000" }
deleted = { bg = "#FF0000", fg = "#000000" }

constant = { fg = "#FF00FF" }
string = { fg = "#00FF00" }
keyword = { fg = "#FFFF00" }
operator = { fg = "#00FFFF" }
type = { fg = "#00FF00" }
preproc = { fg = "#FF00FF" }
special = { fg = "#FF00FF" }
identifier = { fg = "#FF00FF" }

[colors.window.completion]
default = { bg = "#ffffff", fg = "#000000" }
match = { fg = "#00FFFF" }

[colors.window.completion.selected]
default = { bg = "#000000", fg = "#ffffff" }
match = { fg = "#00FFFF" }

[colors.prompt]
default = { bg = "#ffffff", fg = "#000000" }

[colors.prompt.overlay]
default = { bg = "#ffffff", fg = "#000000" }
message = { fg = "#0000FF" }

[colors.prompt.completion]
match = { fg = "#00FFFF" }

[colors.prompt.completion.selected]
default = { bg = "#000000", fg = "#ffffff" }
match = { fg = "#00FFFF" }

[colors.filetree]
default = { bg = "#000000", fg = "#ffffff" }
markers = { fg = "#00FFFF" }
directory = { fg = "#FFFF00" }

[colors.filetree.selected]
default = { bg = "#ffffff", fg = "#000000" }
markers = { fg = "#00FFFF" }

[colors.locations]
default = { bg = "#000000", fg = "#ffffff" }
title = { bg = "#ffffff", fg = "#000000" }
group = { fg = "#FFFF00" }
markers = { fg = "#00FFFF" }
match = { fg = "#00FFFF" }

[colors.locations.selected]
default = { bg = "#ffffff", fg = "#000000" }
match = { fg = "#00FFFF" }
markers = { fg = "#00FFFF" }

[colors.snapshots]
default = { bg = "#000000", fg = "#ffffff" }
graph = { fg = "#00FFFF" }
graph_point = { fg = "#FFFF00" }
# label = { fg = "gray_fg" }
markers = { fg = "#00FFFF" }

[colors.snapshots.selected]
default = { bg = "#ffffff", fg="#000000" }
graph = { fg = "#2d81a3" }
graph_point = { fg = "#000000" }
# label = { fg = "gray_fg" }
markers = { fg = "#00FFFF" }

[colors.popup]
default = { bg = "#ffffff", fg = "#000000" }
