# Colors from https://github.com/chriskempson/tomorrow-theme

[colors.window]
default = { bg = "#1d1f21", fg = "#c5c8c6" }
statusline = { bg = "#373b41", fg = "#c5c8c6" }
statusline_no_focus = { bg = "#282a2e" }
end_of_buffer = { fg = "#969896" }
trailing_whitespace = { fg = "#969896" }
match = { bg = "#f0c674", fg = "#1d1f21" }
virtual = { fg = "#969896" }

[colors.cursor]
normal = { bg = "#81a2be", fg = "#1d1f21" }
selection = { bg = "#373b41" }

[colors.window.view]
hint = { bg = "#8abeb7", fg = "#1d1f21" }
info = { bg = "#81a2be", fg = "#1d1f21" }
warn = { bg = "#f0c674", fg = "#1d1f21" }
error = { bg = "#cc6666", fg = "#1d1f21" }

added = { bg = "#b5bd68", fg = "#1d1f21" }
modified = { bg = "#f0c674", fg = "#1d1f21" }
deleted = { bg = "#cc6666", fg = "#1d1f21" }

constant = { fg = "#81a2be" }
string =  { fg = "#b5bd68" }
keyword = { fg = "#de935f" }
operator =  { fg = "#8abeb7" }
type =  { fg = "#f0c674" }
comment = { fg = "#969896" }
preproc = { fg = "#b294bb" }
special = { fg = "#b294bb" }
identifier = { fg = "#cc6666" }

[colors.window.completion]
default = { bg = "#282a2e", fg = "#c5c8c6" }
description = { fg = "#969896" }
match = { fg = "#de935f" }

[colors.window.completion.selected]
default = { bg = "#373b41" }
description = { fg = "#969896" }
match = { fg = "#de935f" }

[colors.prompt]
default = { bg = "#b5bd68", fg = "#1d1f21" }
message = { }
userinput = { }

[colors.prompt.overlay]
default = { bg = "#282a2e", fg = "#c5c8c6" }
title = { }
message = { fg = "#c5c8c6" }

[colors.prompt.completion]
default = { bg = "#282a2e", fg = "#c5c8c6" }
description = { fg = "#969896" }
match = { fg = "#de935f" }

[colors.prompt.completion.selected]
default = { bg = "#373b41" }
description = { fg = "#969896" }
match = { fg = "#de935f" }

[colors.filetree]
default = { bg = "#1d1f21", fg = "#c5c8c6" }
markers = { fg = "#81a2be" }
directory = { fg = "#b5bd68" }

[colors.filetree.selected]
default = { bg = "#373b41" }
directory = { fg = "#b5bd68" }
markers = { fg = "#81a2be" }

[colors.locations]
default = { bg = "#1d1f21", fg = "#c5c8c6" }
title = { bg = "#373b41", fg = "#c5c8c6" }
# entry = {  }
group = { fg = "#b5bd68" }
markers = { fg = "#81a2be" }
match = { fg = "#de935f" }

[colors.locations.selected]
default = { bg = "#373b41" }
match = { fg = "#de935f" }
markers = { fg = "#81a2be" }
# entry = {  }
group = { fg = "#b5bd68" }

[colors.snapshots]
default = { bg = "#1d1f21", fg = "#c5c8c6" }
graph = { fg = "#b5bd68" }
graph_point = { fg = "#de935f" }
# label = { fg = "gray_fg" }
markers = { fg = "#81a2be" }

[colors.snapshots.selected]
default = { bg = "#373b41" }
graph = { fg = "#b5bd68" }
graph_point = { fg = "#de935f" }
# label = { fg = "fg" }
markers = { fg = "#81a2be" }

[colors.popup]
default = { bg = "#282a2e", fg = "#c5c8c6" }
